# permissions for end users to edit declarativelabels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: declarative-labels-operator
    app.kubernetes.io/managed-by: kustomize
  name: declarativelabels-editor-role
rules:
- apiGroups:
  - webapp.dmpe.github.io
  resources:
  - declarativelabels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.dmpe.github.io
  resources:
  - declarativelabels/status
  verbs:
  - get
