# permissions for end users to view declarativelabels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: declarative-labels-operator
    app.kubernetes.io/managed-by: kustomize
  name: declarativelabels-viewer-role
rules:
- apiGroups:
  - webapp.dmpe.github.io
  resources:
  - declarativelabels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.dmpe.github.io
  resources:
  - declarativelabels/status
  verbs:
  - get
