---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - webapp.dmpe.github.io
  resources:
  - declarativelabels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.dmpe.github.io
  resources:
  - declarativelabels/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.dmpe.github.io
  resources:
  - declarativelabels/status
  verbs:
  - get
  - patch
  - update
