apiVersion: webapp.dmpe.github.io/v1alpha1
kind: DeclarativeLabels
metadata:
  labels:
    app.kubernetes.io/name: declarative-labels-operator
    app.kubernetes.io/managed-by: kustomize
  name: declarativelabels-sample
spec:
  # TODO(user): Add fields here
